# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphic/ui_files/Exit_confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PopUp_Exit_Confirmation(object):
    def setupUi(self, PopUp_Exit_Confirmation):
        PopUp_Exit_Confirmation.setObjectName("PopUp_Exit_Confirmation")
        PopUp_Exit_Confirmation.resize(380, 190)
        self.label = QtWidgets.QLabel(PopUp_Exit_Confirmation)
        self.label.setGeometry(QtCore.QRect(60, 30, 261, 41))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(PopUp_Exit_Confirmation)
        self.buttonBox.setGeometry(QtCore.QRect(100, 80, 161, 51))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(PopUp_Exit_Confirmation)
        QtCore.QMetaObject.connectSlotsByName(PopUp_Exit_Confirmation)

    def retranslateUi(self, PopUp_Exit_Confirmation):
        _translate = QtCore.QCoreApplication.translate
        PopUp_Exit_Confirmation.setWindowTitle(_translate("PopUp_Exit_Confirmation", "Exit Confirmation"))
        self.label.setText(_translate("PopUp_Exit_Confirmation", "Wait! Are you sure you want to exit?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PopUp_Exit_Confirmation = QtWidgets.QDialog()
    ui = Ui_PopUp_Exit_Confirmation()
    ui.setupUi(PopUp_Exit_Confirmation)
    PopUp_Exit_Confirmation.show()
    sys.exit(app.exec_())
